### ISSUE TITLE
Cited WorksLiteraturverzeichnis

### ISSUE THREAD

**Issue by mrchristian** [Health-Sprints/Benchmark#12]
![screencapture-write-healthsprints-org-document-535-2021-08-07-13_01_54](https://user-images.githubusercontent.com/772579/128598020-0fcc8ff4-b571-4346-b722-585ac80873fc.png)

Do we need to have the words 'Cited WorksLiteraturverzeichnis' followed by the local language Bibliography header. 

This is confusing for the editor and looks like an error.

What's the reason for having this?

It would seem better to just have Bibliography, no.

**Comment by johanneswilm** [comment]
@mrchristian Do you have a link for this?

**Comment by johanneswilm** [comment]
@mrchristian The first part ("Cited Works") is there because someone added this in the "Comfy Elephant 2" style that it should prefix the bibliography header with this. You can remove this by removing this part from the the "Comfy Elephant 2" style:

```css
.article-bibliography-header::before {
    content: 'Cited Works';
}
```

The second part ("Literaturverzeichnis") is there because in the article settings, the article is set to be in German language. If you change the language to "English (UK)" it will be changed to "Bibliography".

**Comment by mrchristian** [comment]
Thank you for locating this, I fixed it in Comfy Elephant and Comfy Elefant 2 on health sprints. This needs fixing in the source theme,
